### ISSUE TITLE
Documentation issue in skeleton application tutorial under SQLite3

### ISSUE THREAD

**Issue by chamath** [laminas/tutorials#49]
#### Summary

Go to - [https://docs.laminas.dev/tutorials/getting-started/database-and-models/#sqlite3](https://docs.laminas.dev/tutorials/getting-started/database-and-models/#sqlite3)

After run sqlite command it will create database under project root. So, project will give following error.

An error occurred
An error occurred during execution; please try again later.
Additional information:
PDOException
File:
/var/www/laminasskeleton/vendor/laminas/laminas-db/src/Adapter/Driver/Pdo/Statement.php:159
Message:
SQLSTATE[HY000]: General error: 1 no such table: album
Stack trace:
#0 /var/www/laminasskeleton/vendor/laminas/laminas-db/src/Adapter/Driver/Pdo/Statement.php(159): PDO->prepare(' SELECT "album"...')
#1 /var/www/laminasskeleton/vendor/laminas/laminas-db/src/Adapter/Driver/Pdo/Statement.php(185): Laminas\Db\Adapter\Driver\Pdo\Statement->prepare()
#2 /var/www/laminasskeleton/vendor/laminas/laminas-db/src/TableGateway/AbstractTableGateway.php(228): Laminas\Db\Adapter\Driver\Pdo\Statement->execute()
#3 /var/www/laminasskeleton/vendor/laminas/laminas-db/src/TableGateway/AbstractTableGateway.php(194): Laminas\Db\TableGateway\AbstractTableGateway->executeSelect(Object(Laminas\Db\Sql\Select))
#4 /var/www/laminasskeleton/vendor/laminas/laminas-db/src/TableGateway/AbstractTableGateway.php(183): Laminas\Db\TableGateway\AbstractTableGateway->selectWith(Object(Laminas\Db\Sql\Select))
#5 /var/www/laminasskeleton/module/Album/src/Model/AlbumTable.php(19): Laminas\Db\TableGateway\AbstractTableGateway->select()
#6 /var/www/laminasskeleton/module/Album/src/Controller/AlbumController.php(22): Album\Model\AlbumTable->fetchAll()
#7 /var/www/laminasskeleton/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(71): Album\Controller\AlbumController->indexAction()
#8 /var/www/laminasskeleton/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\Controller\AbstractActionController->onDispatch(Object(Laminas\Mvc\MvcEvent))
#9 /var/www/laminasskeleton/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#10 /var/www/laminasskeleton/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(97): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#11 /var/www/laminasskeleton/vendor/laminas/laminas-mvc/src/DispatchListener.php(132): Laminas\Mvc\Controller\AbstractController->dispatch(Object(Laminas\Http\PhpEnvironment\Request), Object(Laminas\Http\PhpEnvironment\Response))
#12 /var/www/laminasskeleton/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\DispatchListener->onDispatch(Object(Laminas\Mvc\MvcEvent))
#13 /var/www/laminasskeleton/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#14 /var/www/laminasskeleton/vendor/laminas/laminas-mvc/src/Application.php(325): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#15 /var/www/laminasskeleton/public/index.php(50): Laminas\Mvc\Application->run()
#16 {main}

Issue is, database is created in root directory. But project expects in data directory.

#### Current behavior
Documentation tells to run following command.

$ cat data/schema.sql | sqlite3 laminastutorial.db

#### How to reproduce
Run above command. The database file will be created in project root. Not in under data folder. So application unable to find album table.

#### Expected behavior

Database should be in data directory. So, documentation should be updated as follows

$ cat data/schema.sql | sqlite3 data/laminastutorial.db

Thanks
![Screenshot 2021-10-15 194016](https://user-images.githubusercontent.com/2102672/137501188-ad576422-da0f-4b98-bf95-69d44052e07d.png)
s

**Comment by chamath** [comment]
@froschdesign Issue is in here(Under Alternative Commands) - https://docs.laminas.dev/tutorials/getting-started/database-and-models/#sqlite3
